--- 
  - :name: IPI Human
    :keyword: ipi.HUMAN
    :version: 
    :user_uploaded: false
  - :name: IPI Mouse
    :keyword: ipi.MOUSE
    :version: 
    :user_uploaded: false
  - :name: IPI Rat
    :keyword: ipi.RAT
    :version: 
    :user_uploaded: false
  - :name: yeastgenome.org Yeast
    :keyword: orf_trans
    :version: 
    :user_uploaded: false
  - :name: Uniprot Human
    :keyword: 25.H_sapiens
    :version: 
    :user_uploaded: false
  - :name: Uniprot Mouse
    :keyword: 59.M_musculus
    :version: 
    :user_uploaded: false
  - :name: Uniprot Rat
    :keyword: 122.R_norvegicus
    :version: 
    :user_uploaded: false
  - :name: Uniprot Yeast
    :keyword: 40.S_cerevisiae_ATCC_204508
    :version: 
    :user_uploaded: false
  - :name: Uniprot E.Coli
    :keyword: 18.E_coli_K12
    :version: 
    :user_uploaded: false

